### ISSUE TITLE
Remove `body` margin reset

### ISSUE THREAD

**Issue by necolas** [ianstormtaylor/reset#2]
You don't need this code because normalize.css already removes it.

``` css
/**
 * Remove default body margin.
 */

body {
  margin: 0;
}
```
